// Generated by CoffeeScript 2.2.1
(function() {
  /*
    Comentário de várias linhas
  */
  var name, output;

  //# Comentário de uma linha
  name = 'josafa';

  output = document.getElementById("codigo");

  output.innerHTML = `Olá ${name} <br>`;

  if (typeof name === 'string') {
    output.insertAdjacentHTML('beforeend', 'Tipo string <br>');
  }

}).call(this);
