// Generated by CoffeeScript 2.2.1
(function() {
  /*
    browser-sync --server --files "."
    coffee -wc *.coffee
  */
  var i, isBoolean, len, longString, name, output, stringArray, word;

  name = 'josafa';

  output = document.getElementById("codigo");

  output.innerHTML = `Olá ${name} <br>`;

  if (typeof name === 'string') {
    output.insertAdjacentHTML('beforeend', 'Tipo string <br>');
  }

  isBoolean = false;

  if (typeof isBoolean === 'boolean') {
    output.insertAdjacentHTML('beforeend', 'Tipo  boolean! <br>');
  }

  /*
    Interpolação é igual a do ruby!
    ou seja, apenas funciona quando a string estar dentro
    de aspas duplas
  */
  output.insertAdjacentHTML("beforeend", `${5.3456.toFixed(2)} <br>`);

  longString = "String long apenas para teste";

  stringArray = longString.split(" ");

  for (i = 0, len = stringArray.length; i < len; i++) {
    word = stringArray[i];
    output.insertAdjacentHTML("beforeend", word + '<br>');
  }

  // Operações com string praticamente iguais a do java
  output.insertAdjacentHTML('beforeend', longString.length);

}).call(this);
